arm64: add scs_patch_vmlinux prototype
scs_patch_vmlinux() is only called from assembler code, so there
is no prototype, but adding one avoids this warning:

arch/arm64/kernel/patch-scs.c:254:24: error: no previous prototype for function 'scs_patch_vmlinux' [-Werror,-Wmissing-prototypes]

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Acked-by: Ard Biesheuvel <ardb@kernel.org>
Reviewed-by: Kees Cook <keescook@chromium.org>
Message-Id: <20230516160642.523862-3-arnd@kernel.org>